# Generated by Django 5.2.16 on 2026-07-12 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_board_banner_and_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Registered users who may add content to this board', related_name='collab_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
