# Generated by Django 5.2.16 on 2026-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sync_admin_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture, shown wherever the username appears', upload_to='avatars/'),
        ),
    ]
