# Generated by Django 5.2.16 on 2026-07-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='theme',
            field=models.CharField(blank=True, choices=[('', "Viewer's own theme"), ('purple-gold-dark', 'Royal (dark)'), ('neon-cyan-dark', 'Neon Cyan (dark)'), ('emerald-dark', 'Emerald (dark)'), ('ember-dark', 'Ember (dark)'), ('ivory-light', 'Ivory (light)'), ('sky-light', 'Sky (light)'), ('rose-light', 'Rosé (light)')], default='', help_text='Forces a theme for everyone viewing this board', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('purple-gold-dark', 'Royal (dark)'), ('neon-cyan-dark', 'Neon Cyan (dark)'), ('emerald-dark', 'Emerald (dark)'), ('ember-dark', 'Ember (dark)'), ('ivory-light', 'Ivory (light)'), ('sky-light', 'Sky (light)'), ('rose-light', 'Rosé (light)')], default='purple-gold-dark', help_text='Look and feel of Lumivision for this user', max_length=30),
        ),
    ]
