# Generated by Django 5.2.16 on 2026-07-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_board_theme_alter_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_site', models.BooleanField(default=False, help_text='Let anyone browse the home page without signing in. Only Public boards are listed and everything stays view-only for guests.')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
