# Generated by Django 5.2.16 on 2026-07-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_asset_preview',
            field=models.BooleanField(default=False, help_text="Use a blurred collage of the board's first assets as this board's card background in the board list (banner image wins)"),
        ),
    ]
